config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'complaints/index'
  post 'complaints/create'
  get 'complaints/new'
  root 'complaints#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/complaint.rb
class Complaint < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/complaints_controller.rb
# frozen_string_literal: true

class ComplaintsController < ApplicationController
  skip_before_action :verify_authenticity_token

  def index
    @complaints = Complaint.all
  end

  def new
    render 'complaints/new.slim'
  end

  def create
    @complaint = Complaint.create(complaint_params)

    redirect_to :action => "index"
  end

  private

  def complaint_params
    {
      complainer_name: params[:complainer_name],
      date_of_occurrence: Time.zone.parse(params[:occurrence_date]),
      description: params[:description]
    }
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/complaints/index.slim
.container-fluid
  .col-md-12
    h4.h4 Todas as denúncias
    .col-md-12
        .table-responsive.table-responsive-vertical
          table.table.table-hover
            thead.table__header.table__header--dark
              tr.tr
                th.text-left scope='col' Nome do denunciante
                th.text-left scope='col' Data do ocorrido
                th.text-left scope='col' Descrição
                th.text-center scope='col'
            tbody.table__body.table__body--border-thin.table__body--dark-gray
              - @complaints.each do |complaint|
                tr.tr
                  td.td.text-left
                    label.label-value data-label='Nome do denunciante' = complaint.complainer_name
                  td.td.text-left.col-md-1
                    label.label-value data-label='Data do ocorrido' = complaint.date_of_occurrence
                  td.td.text-left.col-md-3
                    label.label-value data-label='Descrição' = complaint.description

app/views/complaints/new.slim
.container-fluid
  .col-md-12
    h4.h4.h4--with-margin-bottom.text-left Envie sua denúncia
    p.small-text.text-left Adicione os dados para enviar sua denúncia!

    = form_tag complaints_create_path, method: :post, id: 'create-complaint', class: 'js-create-complaint-form' do
        .col-md-10
          table.table
            tbody.table__body.table__body--border-thin.table__body--dark-gray.table-responsive-horizontal.js-address-fields
              tr
                th Seu nome
                td.text-left.col-md-7.col-xs-7
                  = text_field_tag :complainer_name, nil, class: 'form-control typeahead', required: false, placeholder: 'ex: Maria dos Santos'
              tr
                th Data de ocorrência
                td.text-left.col-md-7.col-xs-7
                  = text_field_tag :occurrence_date, nil, class: 'form-control typeahead', required: false, placeholder: 'ex: 10/11/2019'
              tr
                th Descrição do ocorrido
                td.text-left.col-md-7.col-xs-7
                  = text_field_tag :description, nil, class: 'form-control typeahead', required: false, placeholder: '....'
          .text-right
            = submit_tag 'Enviar', class: 'btn button button--blue js-create-complaint-button', form: 'create-complaint', id: 'create-complaint-button', disabled: false

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ComplaintApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>